### PR TITLE
Add tools.jar to POM

### PR DESCRIPTION
**Pull request by bootstraponline**
Tools.jar is required to compile.

### CODE REVIEW

**Comment by wuntee** [comment]
What java version/os were you running into this on?

**Comment by bootstraponline** [comment]
According to [Maven's FAQ](https://maven.apache.org/general.html#tools-jar-dependency) "The following code includes tools.jar for JDKs on Windows, Linux and Solaris (it is already included in the runtime for Mac OS X and some free JDKs)."

**Comment by wuntee** [comment]
Yeah, I was just curious as to if you were running into difficulties building the packages, or what? I havent seen any issues without the tools.jar file on osx and Ubuntu (although, I may have been using OpenJDK on Ubuntu)...

**Comment by bootstraponline** [comment]
Eclipse 3.7 complains about unresolved class errors on Ubuntu 11.10 using Oracle JDK 1.7.0_03 64 bit without this patch.

**Comment by bootstraponline** [comment]
The errors without the patch are:

```
Description Resource    Path    Location    Type
ContentSigner cannot be resolved to a type  JarSigner.java  /otertool/src/main/java/com/wuntee/oter/security/tools  line 157    Java Problem
ContentSigner cannot be resolved to a type  JarSigner.java  /otertool/src/main/java/com/wuntee/oter/security/tools  line 381    Java Problem
ContentSigner cannot be resolved to a type  JarSigner.java  /otertool/src/main/java/com/wuntee/oter/security/tools  line 1127   Java Problem
ContentSigner cannot be resolved to a type  JarSigner.java  /otertool/src/main/java/com/wuntee/oter/security/tools  line 1147   Java Problem
ContentSignerParameters cannot be resolved to a type    JarSigner.java  /otertool/src/main/java/com/wuntee/oter/security/tools  line 1232   Java Problem
ContentSignerParameters cannot be resolved to a type    JarSigner.java  /otertool/src/main/java/com/wuntee/oter/security/tools  line 1264   Java Problem
The import com.sun.jarsigner cannot be resolved JarSigner.java  /otertool/src/main/java/com/wuntee/oter/security/tools  line 87 Java Problem
The import com.sun.jarsigner cannot be resolved JarSigner.java  /otertool/src/main/java/com/wuntee/oter/security/tools  line 88 Java Problem
The import sun.security.tools.TimestampedSigner cannot be resolved  JarSigner.java  /otertool/src/main/java/com/wuntee/oter/security/tools  line 76 Java Problem
TimestampedSigner cannot be resolved to a type  JarSigner.java  /otertool/src/main/java/com/wuntee/oter/security/tools  line 1218   Java Problem

```

**Comment by wuntee** [comment]
Can you try and run the 'build-all.sh' and see if anything fails? Or just run 'mvn -f pom-linux-x86.xml clean package' and see if it works? This may just be an eclipse issue.

**Comment by bootstraponline** [comment]
I ran `build-all.sh` and it's the same error.

```
[INFO] 57 warnings 
[INFO] -------------------------------------------------------------
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /otertool/src/main/java/com/wuntee/oter/security/tools/JarSigner.java:[76,25] error: cannot find symbol
[ERROR] /otertool/src/main/java/com/wuntee/oter/security/tools/JarSigner.java:[87,24] error: package com.sun.jarsigner does not exist
[ERROR] /otertool/src/main/java/com/wuntee/oter/security/tools/JarSigner.java:[88,24] error: package com.sun.jarsigner does not exist
[ERROR] /otertool/src/main/java/com/wuntee/oter/security/tools/JarSigner.java:[157,12] error: cannot find symbol
[ERROR] /otertool/src/main/java/com/wuntee/oter/security/tools/JarSigner.java:[1127,12] error: cannot find symbol
[ERROR]  class JarSigner.SignatureFile
/otertool/src/main/java/com/wuntee/oter/security/tools/JarSigner.java:[1147,16] error: cannot find symbol
[ERROR]  class JarSigner.SignatureFile.Block
/otertool/src/main/java/com/wuntee/oter/security/tools/JarSigner.java:[1264,38] error: cannot find symbol
[ERROR] /otertool/src/main/java/com/wuntee/oter/security/tools/JarSigner.java:[1218,39] error: cannot find symbol
[ERROR]  class JarSigner.SignatureFile.Block
/otertool/src/main/java/com/wuntee/oter/security/tools/JarSigner.java:[1232,12] error: cannot find symbol
[INFO] 9 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] -----------------------------------------------------------------------
```

**Pull request closed without merging**
